# For more information, see: https://docs.haskellstack.org/en/stable/yaml_configuration/
# vim: nospell

resolver: lts-13.25

packages:
- .

extra-deps:
- git:    https://github.com/tmcdonell/accelerate.git
  commit: 9251a9fc5895642753e9930642732373c399d0e0

- git:    https://github.com/tmcdonell/accelerate-llvm.git
  commit: 87d49f13ca9f080340d3136e964ea0881848ee9b
  subdirs:
    - accelerate-llvm
    - accelerate-llvm-native
    - accelerate-llvm-ptx

- git:    https://github.com/tmcdonell/accelerate-fft.git
  commit: 1ecec4e16ca30d87ee8d10a63276e02f55f39031

- git:    https://github.com/tmcdonell/lens-accelerate.git
  commit: b74eb8098735b1ad6cff3c5655af03d3f29b9f8e
 
- git:    https://github.com/hspec/HUnit.git
  commit: 691dd02c3137eed621ba042d62f35c3bb70e5b5d

- git:    https://github.com/corsis/clock.git
  commit: 98ff9a0d9aa61382dc8dcda5f74943f5f0029e1a

- git:    https://github.com/chrisdone/formatting.git
  commit: 5baf3b5caa7bc0b51178dedf96d3afbda40c8d99

- cairo-0.13.6.0
- Chart-cairo-1.9.1
- cuda-0.10.1.0
- diagrams-cairo-1.4.1
- glib-0.13.7.0
- gtk2hs-buildtools-0.13.5.0
- hedgehog-1.0
- llvm-hs-8.0.0
- llvm-hs-pure-8.0.0
- pango-0.13.6.0
- tasty-hedgehog-1.0.0.1

# Override default flag values for local packages and extra-deps
flags:
  accelerate:
    debug: true
  accelerate-fft:
    llvm-cpu: true
    llvm-ptx: false

# Extra global and per-package GHC options
# ghc-options: {}

# Extra package databases containing global packages
# extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true

# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: >= 0.1.4.0

# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64

# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]

